#!/bin/bash
# FILENAME:  pcomp_slurm

#SBATCH -A pbermel
#SBATCH -N 1
#SBATCH -n 64
#SBATCH --time=00:45:00

# Change to the directory from which you originally submitted this job.
cd $SLURM_SUBMIT_DIR

# Compile
make o_pcomp

# Run
./pcomp

